#ifndef SMARTPLUGLIB_GLOBAL_H
#define SMARTPLUGLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SMARTPLUGLIB_LIBRARY)
#  define SMARTPLUGLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SMARTPLUGLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SMARTPLUGLIB_GLOBAL_H
